# Generated by Django 3.2.6 on 2022-05-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirst', '0002_carspecs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zakaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zaki_brand', models.CharField(max_length=50)),
                ('zaki_model', models.CharField(max_length=100)),
                ('productions_year', models.CharField(max_length=10)),
                ('zaki_body', models.CharField(max_length=100)),
                ('engine_type', models.CharField(max_length=50)),
            ],
        ),
    ]
