# Generated by Django 3.2.6 on 2022-05-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('car_brand', models.CharField(max_length=100)),
                ('rounds', models.IntegerField(default=0)),
            ],
        ),
    ]
